### ISSUE TITLE
Deploy da API

### ISSUE THREAD

**Issue by jeff-pedro** [jeff-pedro/challenge-backend-jornada-milhas-api#25]
Realizar o deploy automatizado da API em um provedor como **Render**, **GitHub** ou **AWS**.

### Tasks:
- [x] containerizar a aplicação
- [x] testar o deploy manual
- [ ] criar workflow de CI para o testes
- [x] criar workflow de CI para o build
- [x] criar workflow de CI para o deploy

**Comment by jeff-pedro** [comment]
Estou realizando o deploy do banco de dados no Render, porém na versão gratuita dura apenas 1 mês até expirar e o banco ser deletado. Devo futuramente encontrar uma alternativa, talvez um **AWS RDS**?

**Comment by jeff-pedro** [comment]
Foi implementado o deploy da API enviando uma requisição para o Render executar o deploy do último container do Docker Hub. Foi usado o webhook do Render para isso.

Render Docs: https://render.com/docs/deploy-hooks#using-with-github-actions
